
name: Unit Tests Coverage

on:
   pull_request:
    branches:
            - develop
    push:
    branches:
     - "develop"
       

jobs:
  coverage:
        runs-on: ubuntu-latest
    strategy:
      matrix:
       node-version: [15.x]
    
    steps:
      - uses: actions/checkout@v1
      with:
            threshold: 80 
      - name: Git Status
        run: git status
      - name: Install dependencies
        run: npm install
      - name: Test application
        run: npm test