name: Coverage second type
on:
    pull_request:
        branches:
            - develop
jobs:
    coverage:
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
        steps:
            - uses: actions/checkout@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  threshold: 80 # optional parameter
               steps:
          - run : npm install
          - run : npm run test --silent --ci --coverage --coverageReporters=text --coverageReporters=text-summary