
name: Unit Tests Coverage

on:
    push:
    branches:
     - "develop"
       

jobs:
    custom_test:
        runs-on: ubuntu-latest
        name: Test locally using act
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Test coverage
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  threshold: 80 
      - name: Git Status
        run: git status
      - name: Install dependencies
        run: npm install
      - name: Test application
        run: npm test