
name: Unit Test Check

on:
  pull_request:
  push:

 
  
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install modules
        run: npm install

  coverage-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install modules
        run: npm install

      - name: Test Coverage
        run: npm test

  - name: Monitor coverage
        id: coverage-monitor
        if: github.event_name == 'pull_request'
        uses: ./
        with:
          clover_file: "logs/clover.xml"