
name: Unit Test Check

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
       

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install modules
        run: npm install


  coverage-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install modules
        run: npm install

      - name: Test Coverage
        run: npm test
