
name: Unit Test Check

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
 status:
    project:
      default:
        target: auto
        threshold: 90%
        base: auto 
        flags: 
          - unit
        paths: 
          - "src"
        branches: 
          - develop
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false      
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install modules
        run: npm install

  coverage-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install modules
        run: npm install

      - name: Test Coverage
        run: npm test
